--
-- PostgreSQL database dump
--

-- Dumped from database version 12.3
-- Dumped by pg_dump version 12.3

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: Actors; Type: TABLE; Schema: public; Owner: XinghouLiu
--

CREATE TABLE public."Actors" (
    id integer NOT NULL,
    name character varying,
    age integer,
    gender character varying
);


ALTER TABLE public."Actors" OWNER TO "XinghouLiu";

--
-- Name: Actors_id_seq; Type: SEQUENCE; Schema: public; Owner: XinghouLiu
--

CREATE SEQUENCE public."Actors_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Actors_id_seq" OWNER TO "XinghouLiu";

--
-- Name: Actors_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: XinghouLiu
--

ALTER SEQUENCE public."Actors_id_seq" OWNED BY public."Actors".id;


--
-- Name: Movies; Type: TABLE; Schema: public; Owner: XinghouLiu
--

CREATE TABLE public."Movies" (
    id integer NOT NULL,
    title character varying,
    release_date timestamp without time zone
);


ALTER TABLE public."Movies" OWNER TO "XinghouLiu";

--
-- Name: Movies_id_seq; Type: SEQUENCE; Schema: public; Owner: XinghouLiu
--

CREATE SEQUENCE public."Movies_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER TABLE public."Movies_id_seq" OWNER TO "XinghouLiu";

--
-- Name: Movies_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: XinghouLiu
--

ALTER SEQUENCE public."Movies_id_seq" OWNED BY public."Movies".id;


--
-- Name: alembic_version; Type: TABLE; Schema: public; Owner: XinghouLiu
--

CREATE TABLE public.alembic_version (
    version_num character varying(32) NOT NULL
);


ALTER TABLE public.alembic_version OWNER TO "XinghouLiu";

--
-- Name: movie_actor; Type: TABLE; Schema: public; Owner: XinghouLiu
--

CREATE TABLE public.movie_actor (
    movie_id integer NOT NULL,
    actor_id integer NOT NULL
);


ALTER TABLE public.movie_actor OWNER TO "XinghouLiu";

--
-- Name: Actors id; Type: DEFAULT; Schema: public; Owner: XinghouLiu
--

ALTER TABLE ONLY public."Actors" ALTER COLUMN id SET DEFAULT nextval('public."Actors_id_seq"'::regclass);


--
-- Name: Movies id; Type: DEFAULT; Schema: public; Owner: XinghouLiu
--

ALTER TABLE ONLY public."Movies" ALTER COLUMN id SET DEFAULT nextval('public."Movies_id_seq"'::regclass);


--
-- Data for Name: Actors; Type: TABLE DATA; Schema: public; Owner: XinghouLiu
--

COPY public."Actors" (id, name, age, gender) FROM stdin;
2	Actor Two	39	F
3	Actor Three	19	F
\.


--
-- Data for Name: Movies; Type: TABLE DATA; Schema: public; Owner: XinghouLiu
--

COPY public."Movies" (id, title, release_date) FROM stdin;
3	Movie B	2020-12-01 00:00:00
4	Movie D	2020-12-02 00:00:00
5	Movie E	2020-12-02 00:00:00
\.


--
-- Data for Name: alembic_version; Type: TABLE DATA; Schema: public; Owner: XinghouLiu
--

COPY public.alembic_version (version_num) FROM stdin;
8c953ae7fde8
\.


--
-- Data for Name: movie_actor; Type: TABLE DATA; Schema: public; Owner: XinghouLiu
--

COPY public.movie_actor (movie_id, actor_id) FROM stdin;
\.


--
-- Name: Actors_id_seq; Type: SEQUENCE SET; Schema: public; Owner: XinghouLiu
--

SELECT pg_catalog.setval('public."Actors_id_seq"', 3, true);


--
-- Name: Movies_id_seq; Type: SEQUENCE SET; Schema: public; Owner: XinghouLiu
--

SELECT pg_catalog.setval('public."Movies_id_seq"', 5, true);


--
-- Name: Actors Actors_pkey; Type: CONSTRAINT; Schema: public; Owner: XinghouLiu
--

ALTER TABLE ONLY public."Actors"
    ADD CONSTRAINT "Actors_pkey" PRIMARY KEY (id);


--
-- Name: Movies Movies_pkey; Type: CONSTRAINT; Schema: public; Owner: XinghouLiu
--

ALTER TABLE ONLY public."Movies"
    ADD CONSTRAINT "Movies_pkey" PRIMARY KEY (id);


--
-- Name: alembic_version alembic_version_pkc; Type: CONSTRAINT; Schema: public; Owner: XinghouLiu
--

ALTER TABLE ONLY public.alembic_version
    ADD CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num);


--
-- Name: movie_actor movie_actor_pkey; Type: CONSTRAINT; Schema: public; Owner: XinghouLiu
--

ALTER TABLE ONLY public.movie_actor
    ADD CONSTRAINT movie_actor_pkey PRIMARY KEY (movie_id, actor_id);


--
-- Name: movie_actor movie_actor_actor_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: XinghouLiu
--

ALTER TABLE ONLY public.movie_actor
    ADD CONSTRAINT movie_actor_actor_id_fkey FOREIGN KEY (actor_id) REFERENCES public."Actors"(id);


--
-- Name: movie_actor movie_actor_movie_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: XinghouLiu
--

ALTER TABLE ONLY public.movie_actor
    ADD CONSTRAINT movie_actor_movie_id_fkey FOREIGN KEY (movie_id) REFERENCES public."Movies"(id);


--
-- PostgreSQL database dump complete
--

