import os
import unittest
from casting_agency_app import *

# Put a new JWT token here if expired

# Role: Executive Producer (Admin) JWT token
JWT_TOKEN_ADMIN = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkE4UUw4Qy00Y0RoWG5iTlhIS3lJSiJ9.eyJpc3MiOiJodHRwczovL2NvZmZlZS14LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjNmZjI0MDE3MDRhZjAwNmRlNzAwY2QiLCJhdWQiOiJjYXN0aW5nLWFnZW5jeSIsImlhdCI6MTU5ODc5OTcwOCwiZXhwIjoxNTk4ODg2MTA4LCJhenAiOiJycldqWjViM0VnSlBSV3VZaUVJTEo2azFnZVJuc01iaSIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsImRlbGV0ZTptb3ZpZXMiLCJwYXRjaDphY3RvcnMiLCJwYXRjaDptb3ZpZXMiLCJwb3N0OmFjdG9ycyIsInBvc3Q6bW92aWVzIiwicmVhZDphY3RvcnMiLCJyZWFkOm1vdmllcyJdfQ.BnoiC02Kc-PXh0kC5xJZpY8p7rqO6D55PNd15KobgGKY7D7WMIdPg00jeYb8KowpkNrTAq4__30a8WwdEdMrvfyJXLGPrjfmoEqLOBOkDROV7ol-eeMD3qzrvjqNwT_Lz4hWTZVX01nhFi5o7Bh-9-AM90_0tfgRzHyUP2tHRlJ3IxgleD39CWSFhVD46ecQXtoss1l_rp9WAz9sKF2zh-4fSLekJOiYYVs_SSp8Eb-5gEuB1VsrE7Otfcha4Dn8KMkfQLktntZGMbZLwmWk8c0u8SqzBRVausLrkjYJ2Et86iUA9iFSc1ccEpqON_7LipmMMyifEsGDTUrDdcS2OQ'

# Role: Casting Director (Manager) JWT token 
JWT_TOKEN_MANAGER = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkE4UUw4Qy00Y0RoWG5iTlhIS3lJSiJ9.eyJpc3MiOiJodHRwczovL2NvZmZlZS14LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjNmZjIwODk0NjcxMjAwNjc2NDgzYmIiLCJhdWQiOiJjYXN0aW5nLWFnZW5jeSIsImlhdCI6MTU5ODgwMDE0MiwiZXhwIjoxNTk4ODg2NTQyLCJhenAiOiJycldqWjViM0VnSlBSV3VZaUVJTEo2azFnZVJuc01iaSIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsiZGVsZXRlOmFjdG9ycyIsInBhdGNoOmFjdG9ycyIsInBhdGNoOm1vdmllcyIsInBvc3Q6YWN0b3JzIiwicmVhZDphY3RvcnMiLCJyZWFkOm1vdmllcyJdfQ.P-BJLRuDSk3pZjUeUiwbvoHbtBUx1lySGNJZaVmWzv4S07d3vLuwK-9fafb4AXQBH_JAH-IwlTTd2h2RpqDRSrR3_7Pt4ieTUg9dsOlRi92VIhv0U0FqfYJSIMgQlxMc2t_kTUtP6FkpXEx5-BUZ89fqnSj43bV1ZqUGXZMKE9R4JnwnLsK9kpaSj-sY2jHzLVE3JB-Yn2RkQx3zsnKiadUyXyvOWcNnHj4t3ct0-as7Kxnf67Jt96XOJlkP8BnEBD0jxQg7assVJIv3P2MrEd9wyt_PmBQ6rCLDQHZcISbvRMVUYGqBg3qLSwP6sl6BirDrSNmnaNvl7NwpuzNM4w'

# Role: Casting Assistant (User) JWT token
JWT_TOKEN_USER = 'eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IkE4UUw4Qy00Y0RoWG5iTlhIS3lJSiJ9.eyJpc3MiOiJodHRwczovL2NvZmZlZS14LmV1LmF1dGgwLmNvbS8iLCJzdWIiOiJhdXRoMHw1ZjNmZjFjNjMwNDYwYzAwNjc4NTUwYWEiLCJhdWQiOiJjYXN0aW5nLWFnZW5jeSIsImlhdCI6MTU5ODgwMDIwNywiZXhwIjoxNTk4ODg2NjA3LCJhenAiOiJycldqWjViM0VnSlBSV3VZaUVJTEo2azFnZVJuc01iaSIsInNjb3BlIjoiIiwicGVybWlzc2lvbnMiOlsicmVhZDphY3RvcnMiLCJyZWFkOm1vdmllcyJdfQ.BkdyapV1mzDzr9mOWT5gmxtnS86qpdIhNUow4MeFCIGLG-q6S2RPgjVW-f0UxDK53WL351dDZTk5AZzunq7twDvHPA2VwsBD7HDrJi1FBLb9vDRr5krVqgN3WOXUj_fLdf540Qp3a-1LEGGi8Ta_FCViC52msA5YLRrqTEbdd8WBcN-rGq7tNIv08XKnX4meu6EoG6tPHDBP2PRd1y4B-FT-YEHG3MCWD_oneYftmMo4MVxz4q9rwH3dQH6TSrahonspu6MTHtXSMWaa0GLIrL8GPmeuDzWWEDQ28kR2gMe-xVYdhdowxh4jcJ6Y3gzD_Hu3FVfRjjtwKS9Tot_aww'

class BaseTest(unittest.TestCase):
    
    def setUp(self):
        self.app = create_app()
        self.client = self.app.test_client
        self.database_name = "casting_agency_test"
        self.database_path = "postgres://{}/{}".format('localhost:5432', self.database_name) 

        set_up_db(self.app, self.database_path)

        self.admin_header = self.make_header(JWT_TOKEN_ADMIN)
        self.manager_header = self.make_header(JWT_TOKEN_MANAGER)
        self.user_header = self.make_header(JWT_TOKEN_USER)

    
    def make_header(self, token):
        return {
        'Authorization': 'Bearer ' + token
       }
        
